### ISSUE TITLE
I think there is a BodyText Field Enum?

### ISSUE THREAD

**Issue by invokermain** [MarSavar/aletheia#2]
As far as I can see the `bodyText` field is not included in the fields enum. It seems undocumented on the Guardian side, but it also seems very useful.

See for example: https://content.guardianapis.com/search?show-fields=bodyText&page-size=1&api-key=test

**Comment by marsavar** [comment]
Thanks for flagging this @invokermain!
Version `0.1.3` addresses the issue - bumping the library version should allow you to use `Field::BodyText`.
